package org.songdan
import org.songdan.drools.research.model.SpCheckContext
rule "spDiscountCheck_1"
  when
  $context : SpCheckContext( specialDiscount && !discountExpired && openServiceDiscountCls)
  then
  System.out.println("check special discount,context is "+$context);
end

rule "spDiscountCheck_2"
  when
  $context : SpCheckContext( specialDiscount && discountChange)
  then
  System.out.println("check special discount,context is "+$context);
end